name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  # 設定你的 Docker Hub Image 名稱
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mirage_test
  # 設定 Cloud Run 的服務名稱 (自訂，例如 my-web-service)
  SERVICE_NAME: mirage_test
  # 設定 GCP 地區 (例如台灣是 asia-east1)
  REGION: asia-east1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 為了 Cloud Run，我們通常只需要 latest 或是用 SHA 當 tag
      # 這裡示範同時推 latest 和 sha tag
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-cloud-run:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 認證 GCP
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. 部署到 Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # 指定剛剛 Build 好的 Image (使用 SHA tag 確保版本精準)
          image: ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          
          # 如果你的 Dockerfile EXPOSE 不是 8080，這裡要指定
          # flags: '--port=3000' 
          
          # 如果你的服務是公開的 (允許未登入存取)
          flags: '--allow-unauthenticated'

          