# ... 前面的 build-and-push job 保持不變 ...

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.USERNAME }}/my-app/"

      # ▼▼▼ 重點修改這裡 ▼▼▼
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # 1. 這裡要把 GitHub 的 Commit SHA 傳進去 script 裡面
          envs: GITHUB_SHA
          script: |
            cd /home/${{ secrets.USERNAME }}/my-app/
            
            # 2. 設定 TAG 變數
            # 說明：metadata-action 的 type=sha,format=long 會產生 "sha-<完整的commit hash>"
            # 所以我們這裡組合成一樣的字串
            export TAG=sha-${GITHUB_SHA}
            
            # 3. 登入 GHCR (如果你的 Repo 是私有的才需要，公開可省略)
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 4. 拉取特定版本的 Image
            # 注意：這裡前面加了 TAG=$TAG 是為了讓 docker-compose.yml 讀得到變數
            TAG=$TAG docker compose pull

            # 5. 啟動容器
            TAG=$TAG docker compose up -d --remove-orphans
            
            # 6. 清理舊 Image
            docker image prune -f